### ISSUE TITLE
EDC Kit

### ISSUE THREAD

**Issue by mtamigi** [eurotech/edc-examples#3]
The EDC kit with its web dashboard don't work properly.
When the device is provisioned the dashboard can read the state of the demo board (buttons and quad counter), but it can't control the LEDs.

In kura.log you can read this error:
[MQTT Call: 00600C83B323] ERROR o.e.k.c.c.CloudServiceImpl - Error during CloudClientListener notification.
java.text.ParseException: Not a valid request payload
        at org.eclipse.kura.message.KuraRequestPayload.buildFromKuraPayload(KuraRequestPayload.java:57)
        at org.eclipse.kura.core.cloud.CloudServiceImpl.onMessageArrived(CloudServiceImpl.java:468)
        at org.eclipse.kura.core.data.DataServiceListeners.onMessageArrived(DataServiceListeners.java:106)
        at org.eclipse.kura.core.data.DataServiceImpl.onMessageArrived(DataServiceImpl.java:332)
        at org.eclipse.kura.core.data.transport.mqtt.DataTransportListeners.onMessageArrived(DataTransportListeners.java:144)
        at org.eclipse.kura.core.data.transport.mqtt.MqttDataTransport.messageArrived(MqttDataTransport.java:602)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.handleMessage(CommsCallback.java:354)
        at org.eclipse.paho.client.mqttv3.internal.CommsCallback.run(CommsCallback.java:162)
        at java.lang.Thread.run(Thread.java:724)

I've used the 3.1.0 version of ESF on a ReliaGATE10-20.
The idea it's that problem is about the missing signature don't provided from the dashboard.

**Comment by pierrepitiot** [comment]
Hello,

I tested it after rebuilding the edcdevkit example and did not notice any error. Could you please try using the running demo hosted on our Cloud :

http://devkit.everyware-cloud.com/

Subscribe topic = ModbusManager/[your topic] (default is eurotech/demo)
Publish topic = ModbusManager/[your topic]/led

Thanks
--Pierre

**Comment by cdealti** [comment]
Latest changes fix the above issue.
TODO:

- [ ] Upload updated dashboard to devkit.everyware-cloud.com
- [ ] Update documentation correcting the **Publish topic** to **ModbusManager/POST/eurotech/demo**
- [ ] Update documentation for usage with ReliaGATE 10-11

Known Issues:
With Chrome, after refreshing the page the left widgets (Quad Counter gauge, etc) disappear or misbehave.
